// @flow

export default {
  SEARCH_SHOWS: 'SEARCH_SHOWS',
  SEARCH_SHOWS_REQUEST: 'SEARCH_SHOWS_REQUEST',
  SEARCH_SHOWS_SUCCESS: 'SEARCH_SHOWS_SUCCESS',
  SEARCH_SHOWS_ERROR: 'SEARCH_SHOWS_ERROR',
};
